# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{snailgun}
  s.version = "1.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Candler"]
  s.date = %q{2010-05-07}
  s.description = %q{Snailgun accelerates the startup of Ruby applications which require large numbers of libraries}
  s.email = %q{b.candler@pobox.com}
  s.executables = ["fautotest", "fconsole", "fcucumber", "frake", "fruby", "snailgun"]
  s.extra_rdoc_files = [
    "README.markdown",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README.markdown",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/fautotest",
     "bin/fconsole",
     "bin/fcucumber",
     "bin/frake",
     "bin/fruby",
     "bin/snailgun",
     "lib/snailgun/server.rb",
     "snailgun.gemspec"
  ]
  s.homepage = %q{http://github.com/candlerb/snailgun}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Command-line startup accelerator}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

